# Build
FROM maven:3.9.4-eclipse-temurin-17-alpine AS build
WORKDIR /app
COPY pom.xml ./
COPY src ./src
RUN mvn clean package -DskipTests

# Run
FROM eclipse-temurin:17-alpine
WORKDIR /app
COPY --from=build /app/target/*jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]
